### PR TITLE
Form values cleared after "Submit"

### LINKED ISSUE #109: Reset placeholder text
Placeholder text needs to be reset every time the user submits the form (Applicable for every input in frontend)

### PR DESCRIPTION
**Pull request by MyrrhDev**
The values in forms or input fields in:
Login
Register
Search bar
Add posts
are now all cleared after user clicks on "Submit" or chooses a user profile
closes #109

### CODE REVIEW

**Review by bodhisha — APPROVED** [review]
Yeaaa.. That looks Perfect!! 🎉

**Review by aitikgupta — APPROVED** [review]
This looks perfect, thank you so much @MyrrhDev! 🎉

**Comment by aitikgupta** [comment]
Preview URL: https://60782351c5466f000891e088--sociomark.netlify.app/

**Comment by aitikgupta** [comment]
@MyrrhDev can you rebase the PR?

**Review by bodhisha — APPROVED** [review]

**Pull request merged**
