### PR TITLE
PWA setup

### LINKED ISSUE #111: Make SocioMark a progressive Web Application

### PR DESCRIPTION
**Pull request by bodhisha**
Resolves #111 

**Changes**
- Now Sociomark is a PWA
- It can be directly installed on user’s home screen
https://user-images.githubusercontent.com/34866653/114833746-88a11480-9ded-11eb-96c3-c0df68616796.mp4

### CODE REVIEW

**Review by aitikgupta — APPROVED** [review]
OMG. I can't believe the wonders of PWA (didn't totally jump off when I saw the local version of SocioMark)
image

This is amazing @bodhisha 🎉

**Comment by aitikgupta** [comment]
You might wanna add some information in the README @bodhisha (with some graphics, ofcourse :p)

**Comment by bodhisha** [comment]
> You might wanna add some information in the README @bodhisha (with some graphics, ofcourse :p)

Yeaa.. Will add some stuff in README too

**Review by DebugAgrawal — APPROVED** [review]
> #### PWA is Amazing 🙌🚀
#### `SocioMark Now easier to access and use ✨`

**Pull request merged**
